// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	ID       string `gorm:"column:id;primaryKey" json:"id"`
	Phone    string `gorm:"column:phone;not null" json:"phone"`
	Nickname string `gorm:"column:nickname;not null" json:"nickname"`
	Password string `gorm:"column:password;not null" json:"password"`
	Salt     string `gorm:"column:salt;not null" json:"salt"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
