// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

const TableNameGood = "goods"

// Good mapped from table <goods>
type Good struct {
	ID            string          `gorm:"column:id;primaryKey" json:"id"`
	Name          string          `gorm:"column:name;not null" json:"name"`
	Img           string          `gorm:"column:img;not null" json:"img"`
	Price         decimal.Decimal `gorm:"column:price;not null" json:"price"`
	OriginalPrice decimal.Decimal `gorm:"column:original_price;not null" json:"original_price"`
	CreateAt      time.Time       `gorm:"column:create_at;not null" json:"create_at"`
	UpdatedAt     time.Time       `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt     gorm.DeletedAt  `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Desc          string          `gorm:"column:desc;not null" json:"desc"`
}

// TableName Good's table name
func (*Good) TableName() string {
	return TableNameGood
}
